[workspace]
changelog_update = false
git_tag_enable = true
git_tag_name = "{{ version }}"
release_commits = "^feat[(:]"
publish = false

[changelog]
trim = true
sort_commits = "newest"

commit_preprocessors = [
  # remove issue numbers from commits
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]

commit_parsers = [
    { message = "^feat", group = "added" },
    { message = "^.*: support", group = "added" },
    { body = ".*feat", group = "added" },
    { message = "^changed", group = "changed" },
    { message = "^deprecated", group = "deprecated" },
    { message = "^.*: remove", group = "deprecated" },
    { message = "^.*: delete", group = "deprecated" },
    { message = "^(fix|test)", group = "fixed" },
    { body = ".*(fix|test)", group = "fixed" },
    { message = "^.*: fix", group = "fixed" },
    { message = "^security", group = "security" },
    { message = "^.*", group = "other" },
]
